# Generated by Django 4.1.7 on 2023-03-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_configtrade_description_configtrade_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='price',
            new_name='last_trade_price',
        ),
        migrations.AddField(
            model_name='trade',
            name='first_asks',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='first_bids',
            field=models.FloatField(null=True),
        ),
    ]
